interface User {
    id : number,
    name : string,
    role : string,
    address : string,
    salary : number,
};

export const users : User[] = [
    {
    id: 1,
    name: 'Nadia',
    role: 'Developer',
    address: '456',
    salary: 180,
    },
    {
    id: 2,
    name: 'Mason',
    role: 'Manager',
    address: '654',
    salary: 230,
    },
    {
    id: 3,
    name: 'Lena',
    role: 'Marketing',
    address: '789',
    salary: 140,
    },
    {
    id: 4,
    name: 'Harrison',
    role: 'Marketing',
    address: '123',
    salary: 190,
    },
    {
    id: 5,
    name: 'Ella',
    role: 'HR',
    address: '987',
    salary: 30,
    },
    {
    id: 6,
    name: 'Oliver',
    role: 'Developer',
    address: '321',
    salary: 160,
    },
    {
    id: 7,
    name: 'Grace',
    role: 'Manager',
    address: '654',
    salary: 220,
    },
    {
    id: 8,
    name: 'Ian',
    role: 'Marketing',
    address: '987',
    salary: 150,
    },
    {
    id: 9,
    name: 'Gia',
    role: 'Marketing',
    address: '456',
    salary: 200,
    },
    {
    id: 10,
    name: 'Carter',
    role: 'HR',
    address: '789',
    salary: 40,
    },
    {
    id: 11,
    name: 'Aria',
    role: 'Developer',
    address: '123',
    salary: 170,
    },
    {
    id: 12,
    name: 'Leo',
    role: 'Manager',
    address: '456',
    salary: 240,
    },
    {
    id: 13,
    name: 'Natalie',
    role: 'Marketing',
    address: '789',
    salary: 130,
    },
    {
    id: 14,
    name: 'Maxwell',
    role: 'Marketing',
    address: '654',
    salary: 210,
    },
    {
    id: 15,
    name: 'Avery',
    role: 'HR',
    address: '321',
    salary: 50,
    },
    {
    id: 16,
    name: 'Isaac',
    role: 'Developer',
    address: '987',
    salary: 190,
    },
    {
    id: 17,
    name: 'Audrey',
    role: 'Manager',
    address: '123',
    salary: 250,
    },
    {
    id: 18,
    name: 'Ethan',
    role: 'Marketing',
    address: '456',
    salary: 160,
    },
    {
    id: 19,
    name: 'Arianna',
    role: 'Marketing',
    address: '789',
    salary: 170,
    },
    {
    id: 20,
    name: 'Oscar',
    role: 'HR',
    address: '654',
    salary: 60,
    },
    ];